config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  root to: 'products#index'

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end
  
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post    :add_item
    post :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
    resources :sales, only: [:index, :new, :create]
  end
  resource :about

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def show
    @products = Product.count
    @categories = Category.count
  end
end

app/views/admin/dashboard/show.html.erb
<header class='page-header'>
<h1>Dashboard</h1>
</header>

<div class="panel panel-primary">
 <div class="panel-heading">
   <h4> Total Number of Products</h4>
  </div>
  <div class="panel-body">
 <h5> <%= @products %></h5>
 <br>
<%= link_to 'Products', admin_products_path %>
  </div>
</div>
<div class="panel panel-primary">
 <div class="panel-heading">
   <h4> Total Number of Categories </h4>
  </div>
  <div class="panel-body">
  <h5><%= @categories %></h5>
  <br>
  <%= link_to 'Categories', admin_categories_path %>
  </div>
</div>